# Generated by Django 4.0.3 on 2022-03-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name_of_brand',
            new_name='name',
        ),
    ]
